Gallery
Yermolinn/Shop-for-gamers pull request #3
Opened 2022-11-19 20:03 UTC by andybod

привіт, закінчив верстати галерею окрім background

2022-11-20 13:18 UTC, Yermolinn requested changes

2022-11-20 13:18 UTC, Yermolinn commented on src/sass/layouts/_gallery.scss
> +  background: #000;
в mobile, tablet section фон чорний, тобто не підгружає background-image. Треба підправити.

2022-11-20 13:18 UTC, Yermolinn commented on src/sass/layouts/_gallery.scss
> +  font-style: 24px;
якщо є бажання можеш використати mixin

@mixin font($fw, $fs, $lh, $ls) {
    font-weight: $fw;
    font-size: $fs;
    line-height: $lh;
    letter-spacing: $ls;
}

2022-11-20 17:55 UTC, andybod commented on src/sass/layouts/_gallery.scss
> +  background: #000;
вже змінив

2022-11-20 17:56 UTC, andybod commented on src/sass/layouts/_gallery.scss
> +  font-style: 24px;
ні не хочу (

2022-11-20 22:14 UTC, Yermolinn requested changes

2022-11-20 22:14 UTC, Yermolinn commented on src/sass/layouts/_gallery.scss
> +    padding-left: 55px;
padding-left зайвий

2022-11-20 22:14 UTC, Yermolinn commented on src/sass/layouts/_gallery.scss
> +  font-weight: 500;
змінити на 600

2022-11-21 12:54 UTC, andybod commented on src/sass/layouts/_gallery.scss
> +  font-weight: 500;
це робото там повинно бути 500

2022-11-21 13:29 UTC, Yermolinn reviewed
Готово

2022-11-21 13:34 UTC, merged