Feature/sale
Yermolinn/Shop-for-gamers pull request #5
Opened 2022-11-20 19:58 UTC by anthonyhorvat

Виконана вся розмітка секції Sale з додаваннями стилів.
Відсутні поки що лінії SVG.

2022-11-21 12:23 UTC, Yermolinn requested changes

2022-11-21 12:23 UTC, Yermolinn commented on src/partials/sale.html
> +          <div class="sale__item-bottom">
підшаманити USD

2022-11-21 18:10 UTC, anthonyhorvat commented on src/partials/sale.html
> +          <div class="sale__item-bottom">
Виправлено

2022-11-22 06:24 UTC, Yermolinn approved these changes

2022-11-22 06:24 UTC, merged