Add bottom part of section "order"
Yermolinn/Shop-for-gamers pull request #6
Opened 2022-11-20 21:09 UTC by Maksym111

Зробив нижню частину секції "take order", верхню робить Андрій, бо ми розбили розділ на 2 частини. Будь-ласка, перевір чи все вірно.

2022-11-21 13:45 UTC, Yermolinn requested changes

2022-11-21 13:45 UTC, Yermolinn commented on src/sass/layouts/_order.scss
> +.main-btn:hover,
додати плавний ховер для кнопок всередені модалки

2022-11-21 16:55 UTC, Maksym111 commented on src/sass/layouts/_order.scss
> +.main-btn:hover,
Зроблено!

2022-11-21 16:56 UTC, Maksym111 reviewed
Виправив помилки та додав ховер

2022-11-21 19:28 UTC, Maksym111 reviewed
Додав ще лінку, через яку не працювала модалка. Наразі усе працює)

2022-11-22 07:05 UTC, Yermolinn approved these changes

2022-11-22 07:05 UTC, merged